[project]
name = "LevBoard"
version = "0.1"
description = "A stats.fm integration for building custom charts."
readme = "README.md"
dependencies = [
    "flask",
    "pydantic",
    "requests",
]

[project.optional-dependencies]
test = ["pytest"]